// src/lib/mockDb.js - Mock data for headcount + orgchart demo

export const businessFunctions = [
  { id: 1, name: "Information Technology", code: "IT", is_active: true, employee_count: 6 },
  { id: 2, name: "Finance", code: "FIN", is_active: true, employee_count: 4 },
  { id: 3, name: "Human Resources", code: "HR", is_active: true, employee_count: 4 },
  { id: 4, name: "Operations", code: "OPS", is_active: true, employee_count: 6 },
  { id: 5, name: "Sales & Marketing", code: "SALES", is_active: true, employee_count: 5 },
];

export const departments = [
  { id: 1, name: "Software Development", business_function: 1, business_function_name: "Information Technology", is_active: true, employee_count: 4 },
  { id: 2, name: "IT Infrastructure", business_function: 1, business_function_name: "Information Technology", is_active: true, employee_count: 2 },
  { id: 3, name: "Financial Planning", business_function: 2, business_function_name: "Finance", is_active: true, employee_count: 2 },
  { id: 4, name: "Accounting", business_function: 2, business_function_name: "Finance", is_active: true, employee_count: 2 },
  { id: 5, name: "Talent Acquisition", business_function: 3, business_function_name: "Human Resources", is_active: true, employee_count: 2 },
  { id: 6, name: "HR Operations", business_function: 3, business_function_name: "Human Resources", is_active: true, employee_count: 2 },
  { id: 7, name: "Supply Chain", business_function: 4, business_function_name: "Operations", is_active: true, employee_count: 3 },
  { id: 8, name: "Customer Service", business_function: 4, business_function_name: "Operations", is_active: true, employee_count: 3 },
  { id: 9, name: "Sales", business_function: 5, business_function_name: "Sales & Marketing", is_active: true, employee_count: 3 },
  { id: 10, name: "Marketing", business_function: 5, business_function_name: "Sales & Marketing", is_active: true, employee_count: 2 },
];

export const positions = [
  { id: 1, name: "Chief Executive Officer", code: "CEO", department: null, is_active: true },
  { id: 2, name: "Chief Technology Officer", code: "CTO", department: 1, is_active: true },
  { id: 3, name: "Chief Financial Officer", code: "CFO", department: 3, is_active: true },
  { id: 4, name: "Chief People Officer", code: "CPO", department: 5, is_active: true },
  { id: 5, name: "VP of Operations", code: "VPO", department: 7, is_active: true },
  { id: 6, name: "VP of Sales", code: "VPS", department: 9, is_active: true },
  { id: 7, name: "Senior Software Engineer", code: "SSE", department: 1, is_active: true },
  { id: 8, name: "Software Engineer", code: "SE", department: 1, is_active: true },
  { id: 9, name: "DevOps Engineer", code: "DOE", department: 2, is_active: true },
  { id: 10, name: "Financial Analyst", code: "FA", department: 3, is_active: true },
  { id: 11, name: "Accountant", code: "ACC", department: 4, is_active: true },
  { id: 12, name: "HR Business Partner", code: "HRBP", department: 5, is_active: true },
  { id: 13, name: "Recruiter", code: "REC", department: 5, is_active: true },
  { id: 14, name: "Sales Manager", code: "SM", department: 9, is_active: true },
  { id: 15, name: "Sales Representative", code: "SR", department: 9, is_active: true },
];

// Build photo URL helper
const photo = (name) => `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=random&size=128`;

// In-memory store (mutable for demo mutations)
let _employees = [
  {
    id: 1,
    first_name: "Elnur",
    last_name: "Mammadov",
    email: "elnur.mammadov@company.az",
    phone: "+994501234001",
    position: 1,
    position_name: "Chief Executive Officer",
    department: null,
    department_name: null,
    business_function: null,
    business_function_name: null,
    manager_id: null,
    line_manager: null,
    line_manager_name: null,
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2018-01-15",
    employment_type: "FULL_TIME",
    photo: photo("Elnur Mammadov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 2,
    first_name: "Aytən",
    last_name: "Əliyeva",
    email: "ayten.aliyeva@company.az",
    phone: "+994501234002",
    position: 2,
    position_name: "Chief Technology Officer",
    department: 1,
    department_name: "Software Development",
    business_function: 1,
    business_function_name: "Information Technology",
    manager_id: 1,
    line_manager: 1,
    line_manager_name: "Elnur Mammadov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2019-03-01",
    employment_type: "FULL_TIME",
    photo: photo("Aytən Əliyeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 3,
    first_name: "Kamran",
    last_name: "Həsənov",
    email: "kamran.hasanov@company.az",
    phone: "+994501234003",
    position: 3,
    position_name: "Chief Financial Officer",
    department: 3,
    department_name: "Financial Planning",
    business_function: 2,
    business_function_name: "Finance",
    manager_id: 1,
    line_manager: 1,
    line_manager_name: "Elnur Mammadov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2019-05-10",
    employment_type: "FULL_TIME",
    photo: photo("Kamran Həsənov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 4,
    first_name: "Nigar",
    last_name: "Quliyeva",
    email: "nigar.quliyeva@company.az",
    phone: "+994501234004",
    position: 4,
    position_name: "Chief People Officer",
    department: 5,
    department_name: "Talent Acquisition",
    business_function: 3,
    business_function_name: "Human Resources",
    manager_id: 1,
    line_manager: 1,
    line_manager_name: "Elnur Mammadov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2019-07-22",
    employment_type: "FULL_TIME",
    photo: photo("Nigar Quliyeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 5,
    first_name: "Rauf",
    last_name: "İsmayılov",
    email: "rauf.ismayilov@company.az",
    phone: "+994501234005",
    position: 5,
    position_name: "VP of Operations",
    department: 7,
    department_name: "Supply Chain",
    business_function: 4,
    business_function_name: "Operations",
    manager_id: 1,
    line_manager: 1,
    line_manager_name: "Elnur Mammadov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-01-06",
    employment_type: "FULL_TIME",
    photo: photo("Rauf İsmayılov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 6,
    first_name: "Sevinc",
    last_name: "Babayeva",
    email: "sevinc.babayeva@company.az",
    phone: "+994501234006",
    position: 6,
    position_name: "VP of Sales",
    department: 9,
    department_name: "Sales",
    business_function: 5,
    business_function_name: "Sales & Marketing",
    manager_id: 1,
    line_manager: 1,
    line_manager_name: "Elnur Mammadov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-02-17",
    employment_type: "FULL_TIME",
    photo: photo("Sevinc Babayeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 7,
    first_name: "Fərid",
    last_name: "Nəcəfov",
    email: "farid.nacafov@company.az",
    phone: "+994501234007",
    position: 7,
    position_name: "Senior Software Engineer",
    department: 1,
    department_name: "Software Development",
    business_function: 1,
    business_function_name: "Information Technology",
    manager_id: 2,
    line_manager: 2,
    line_manager_name: "Aytən Əliyeva",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-04-13",
    employment_type: "FULL_TIME",
    photo: photo("Fərid Nəcəfov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 8,
    first_name: "Lalə",
    last_name: "Rəhimova",
    email: "lale.rahimova@company.az",
    phone: "+994501234008",
    position: 8,
    position_name: "Software Engineer",
    department: 1,
    department_name: "Software Development",
    business_function: 1,
    business_function_name: "Information Technology",
    manager_id: 7,
    line_manager: 7,
    line_manager_name: "Fərid Nəcəfov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2021-06-01",
    employment_type: "FULL_TIME",
    photo: photo("Lalə Rəhimova"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 9,
    first_name: "Tural",
    last_name: "Abbasov",
    email: "tural.abbasov@company.az",
    phone: "+994501234009",
    position: 8,
    position_name: "Software Engineer",
    department: 1,
    department_name: "Software Development",
    business_function: 1,
    business_function_name: "Information Technology",
    manager_id: 7,
    line_manager: 7,
    line_manager_name: "Fərid Nəcəfov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2021-09-15",
    employment_type: "FULL_TIME",
    photo: photo("Tural Abbasov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 10,
    first_name: "Günel",
    last_name: "Musayeva",
    email: "gunel.musayeva@company.az",
    phone: "+994501234010",
    position: 9,
    position_name: "DevOps Engineer",
    department: 2,
    department_name: "IT Infrastructure",
    business_function: 1,
    business_function_name: "Information Technology",
    manager_id: 2,
    line_manager: 2,
    line_manager_name: "Aytən Əliyeva",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-11-23",
    employment_type: "FULL_TIME",
    photo: photo("Günel Musayeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 11,
    first_name: "Murad",
    last_name: "Cəfərov",
    email: "murad.cafarov@company.az",
    phone: "+994501234011",
    position: 9,
    position_name: "DevOps Engineer",
    department: 2,
    department_name: "IT Infrastructure",
    business_function: 1,
    business_function_name: "Information Technology",
    manager_id: 10,
    line_manager: 10,
    line_manager_name: "Günel Musayeva",
    status: "PROBATION",
    status_name: "Probation",
    start_date: "2023-08-01",
    employment_type: "FULL_TIME",
    photo: photo("Murad Cəfərov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 12,
    first_name: "Xədicə",
    last_name: "Orucova",
    email: "xadica.orucova@company.az",
    phone: "+994501234012",
    position: 10,
    position_name: "Financial Analyst",
    department: 3,
    department_name: "Financial Planning",
    business_function: 2,
    business_function_name: "Finance",
    manager_id: 3,
    line_manager: 3,
    line_manager_name: "Kamran Həsənov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-08-10",
    employment_type: "FULL_TIME",
    photo: photo("Xədicə Orucova"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 13,
    first_name: "Samir",
    last_name: "Hüseynov",
    email: "samir.huseynov@company.az",
    phone: "+994501234013",
    position: 10,
    position_name: "Financial Analyst",
    department: 3,
    department_name: "Financial Planning",
    business_function: 2,
    business_function_name: "Finance",
    manager_id: 3,
    line_manager: 3,
    line_manager_name: "Kamran Həsənov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2021-01-18",
    employment_type: "FULL_TIME",
    photo: photo("Samir Hüseynov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 14,
    first_name: "Zəhra",
    last_name: "Ağayeva",
    email: "zahra.agayeva@company.az",
    phone: "+994501234014",
    position: 11,
    position_name: "Accountant",
    department: 4,
    department_name: "Accounting",
    business_function: 2,
    business_function_name: "Finance",
    manager_id: 3,
    line_manager: 3,
    line_manager_name: "Kamran Həsənov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-06-15",
    employment_type: "FULL_TIME",
    photo: photo("Zəhra Ağayeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 15,
    first_name: "Orxan",
    last_name: "Sultanov",
    email: "orxan.sultanov@company.az",
    phone: "+994501234015",
    position: 11,
    position_name: "Accountant",
    department: 4,
    department_name: "Accounting",
    business_function: 2,
    business_function_name: "Finance",
    manager_id: 14,
    line_manager: 14,
    line_manager_name: "Zəhra Ağayeva",
    status: "ONBOARDING",
    status_name: "Onboarding",
    start_date: "2024-02-05",
    employment_type: "FULL_TIME",
    photo: photo("Orxan Sultanov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 16,
    first_name: "Leyla",
    last_name: "Rzayeva",
    email: "leyla.rzayeva@company.az",
    phone: "+994501234016",
    position: 12,
    position_name: "HR Business Partner",
    department: 5,
    department_name: "Talent Acquisition",
    business_function: 3,
    business_function_name: "Human Resources",
    manager_id: 4,
    line_manager: 4,
    line_manager_name: "Nigar Quliyeva",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-09-21",
    employment_type: "FULL_TIME",
    photo: photo("Leyla Rzayeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 17,
    first_name: "Vüsal",
    last_name: "Əhmədov",
    email: "vusal.ahmadov@company.az",
    phone: "+994501234017",
    position: 13,
    position_name: "Recruiter",
    department: 5,
    department_name: "Talent Acquisition",
    business_function: 3,
    business_function_name: "Human Resources",
    manager_id: 16,
    line_manager: 16,
    line_manager_name: "Leyla Rzayeva",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2021-11-08",
    employment_type: "FULL_TIME",
    photo: photo("Vüsal Əhmədov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 18,
    first_name: "Aynur",
    last_name: "Məmmədova",
    email: "aynur.mammadova@company.az",
    phone: "+994501234018",
    position: 13,
    position_name: "Recruiter",
    department: 6,
    department_name: "HR Operations",
    business_function: 3,
    business_function_name: "Human Resources",
    manager_id: 4,
    line_manager: 4,
    line_manager_name: "Nigar Quliyeva",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2022-03-14",
    employment_type: "PART_TIME",
    photo: photo("Aynur Məmmədova"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 19,
    first_name: "Elnur",
    last_name: "Qasımov",
    email: "elnur.qasimov@company.az",
    phone: "+994501234019",
    position: 15,
    position_name: "Sales Representative",
    department: 7,
    department_name: "Supply Chain",
    business_function: 4,
    business_function_name: "Operations",
    manager_id: 5,
    line_manager: 5,
    line_manager_name: "Rauf İsmayılov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2021-05-03",
    employment_type: "FULL_TIME",
    photo: photo("Elnur Qasımov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 20,
    first_name: "Şəbnəm",
    last_name: "Kərimova",
    email: "sabnam.karimova@company.az",
    phone: "+994501234020",
    position: 15,
    position_name: "Sales Representative",
    department: 7,
    department_name: "Supply Chain",
    business_function: 4,
    business_function_name: "Operations",
    manager_id: 5,
    line_manager: 5,
    line_manager_name: "Rauf İsmayılov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2021-07-19",
    employment_type: "FULL_TIME",
    photo: photo("Şəbnəm Kərimova"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 21,
    first_name: "Cavid",
    last_name: "Rəsulov",
    email: "cavid.rasulov@company.az",
    phone: "+994501234021",
    position: 15,
    position_name: "Sales Representative",
    department: 8,
    department_name: "Customer Service",
    business_function: 4,
    business_function_name: "Operations",
    manager_id: 5,
    line_manager: 5,
    line_manager_name: "Rauf İsmayılov",
    status: "ON_LEAVE",
    status_name: "On Leave",
    start_date: "2020-12-07",
    employment_type: "FULL_TIME",
    photo: photo("Cavid Rəsulov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 22,
    first_name: "Nərmin",
    last_name: "İbrahimova",
    email: "narmin.ibrahimova@company.az",
    phone: "+994501234022",
    position: 15,
    position_name: "Sales Representative",
    department: 8,
    department_name: "Customer Service",
    business_function: 4,
    business_function_name: "Operations",
    manager_id: 5,
    line_manager: 5,
    line_manager_name: "Rauf İsmayılov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2022-01-24",
    employment_type: "FULL_TIME",
    photo: photo("Nərmin İbrahimova"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 23,
    first_name: "Əli",
    last_name: "Novruzov",
    email: "ali.novruzov@company.az",
    phone: "+994501234023",
    position: 14,
    position_name: "Sales Manager",
    department: 9,
    department_name: "Sales",
    business_function: 5,
    business_function_name: "Sales & Marketing",
    manager_id: 6,
    line_manager: 6,
    line_manager_name: "Sevinc Babayeva",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2020-10-05",
    employment_type: "FULL_TIME",
    photo: photo("Əli Novruzov"),
    gender: "M",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 24,
    first_name: "Rəna",
    last_name: "Mirzəyeva",
    email: "rana.mirzayeva@company.az",
    phone: "+994501234024",
    position: 15,
    position_name: "Sales Representative",
    department: 9,
    department_name: "Sales",
    business_function: 5,
    business_function_name: "Sales & Marketing",
    manager_id: 23,
    line_manager: 23,
    line_manager_name: "Əli Novruzov",
    status: "ACTIVE",
    status_name: "Active",
    start_date: "2022-06-13",
    employment_type: "FULL_TIME",
    photo: photo("Rəna Mirzəyeva"),
    gender: "F",
    is_active: true,
    is_visible_in_org_chart: true,
  },
  {
    id: 25,
    first_name: "Bəhruz",
    last_name: "Tahirov",
    email: "bahruz.tahirov@company.az",
    phone: "+994501234025",
    position: 15,
    position_name: "Sales Representative",
    department: 10,
    department_name: "Marketing",
    business_function: 5,
    business_function_name: "Sales & Marketing",
    manager_id: 6,
    line_manager: 6,
    line_manager_name: "Sevinc Babayeva",
    status: "INACTIVE",
    status_name: "Inactive",
    start_date: "2019-11-11",
    employment_type: "FULL_TIME",
    photo: photo("Bəhruz Tahirov"),
    gender: "M",
    is_active: false,
    is_visible_in_org_chart: false,
  },
];

// ── Helper: get employees (returns a shallow copy so mutations don't break list) ──
export function getEmployees() {
  return [..._employees];
}

export function getEmployeeById(id) {
  const numId = parseInt(id, 10);
  return _employees.find((e) => e.id === numId) || null;
}

export function createEmployeeRecord(data) {
  const newId = Math.max(..._employees.map((e) => e.id)) + 1;
  const newEmployee = {
    id: newId,
    first_name: data.first_name || "",
    last_name: data.last_name || "",
    email: data.email || `employee${newId}@company.az`,
    phone: data.phone || "",
    position: data.position || null,
    position_name: data.position_name || null,
    department: data.department || null,
    department_name: data.department_name || null,
    business_function: data.business_function || null,
    business_function_name: data.business_function_name || null,
    manager_id: data.manager_id || data.line_manager || null,
    line_manager: data.line_manager || data.manager_id || null,
    line_manager_name: data.line_manager_name || null,
    status: data.status || "ONBOARDING",
    status_name: data.status_name || "Onboarding",
    start_date: data.start_date || new Date().toISOString().split("T")[0],
    employment_type: data.employment_type || "FULL_TIME",
    photo:
      data.photo ||
      photo(`${data.first_name || "New"} ${data.last_name || "Employee"}`),
    gender: data.gender || "M",
    is_active: data.is_active !== false,
    is_visible_in_org_chart: data.is_visible_in_org_chart !== false,
    ...data,
    id: newId,
  };
  _employees.push(newEmployee);
  return newEmployee;
}

export function updateEmployeeRecord(id, data) {
  const numId = parseInt(id, 10);
  const idx = _employees.findIndex((e) => e.id === numId);
  if (idx === -1) return null;
  _employees[idx] = { ..._employees[idx], ...data, id: numId };
  return _employees[idx];
}

export function deleteEmployeeRecord(id) {
  const numId = parseInt(id, 10);
  const idx = _employees.findIndex((e) => e.id === numId);
  if (idx === -1) return false;
  _employees.splice(idx, 1);
  return true;
}

// ── Org Chart helpers ──────────────────────────────────────────────────────────

/**
 * Build a tree of nodes for the org chart.
 * Each node: { employee_id, name, position_name, department_name, photo, status, children: [] }
 */
export function getOrgChartData(params = {}) {
  const visible = _employees.filter((e) => e.is_visible_in_org_chart !== false);

  const map = {};
  visible.forEach((e) => {
    map[e.id] = {
      employee_id: e.id,
      id: e.id,
      name: `${e.first_name} ${e.last_name}`,
      first_name: e.first_name,
      last_name: e.last_name,
      email: e.email,
      phone: e.phone,
      position_name: e.position_name,
      position: e.position,
      department_name: e.department_name,
      department: e.department,
      business_function_name: e.business_function_name,
      business_function: e.business_function,
      line_manager_id: e.manager_id || e.line_manager,
      status: e.status,
      status_name: e.status_name,
      photo: e.photo,
      employment_type: e.employment_type,
      start_date: e.start_date,
      children: [],
    };
  });

  const roots = [];
  Object.values(map).forEach((node) => {
    if (node.line_manager_id && map[node.line_manager_id]) {
      map[node.line_manager_id].children.push(node);
    } else {
      roots.push(node);
    }
  });

  return roots;
}
